<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-04JSCC6" name="datadriven.testscript.TC002MapSearchPage" tests="3" failures="0" timestamp="26 Jun 2019 04:20:19 GMT" time="104.253" errors="1">
  <testcase name="SearchPageTest" time="53.003" classname="datadriven.testscript.TC002MapSearchPage"/>
  <testcase name="DataProviderTest" time="5.058" classname="datadriven.testscript.TC002MapSearchPage">
    <error type="org.testng.TestNGException" message="
Method public void datadriven.testscript.TC002MapSearchPage.DataProviderTest(datadriven.dataprovider.ExcelDataProviderObject) throws java.lang.InterruptedException requires a @DataProvider named : getData in class datadriven.dataprovider.ExcelDataProvider">
      <![CDATA[org.testng.TestNGException: 
Method public void datadriven.testscript.TC002MapSearchPage.DataProviderTest(datadriven.dataprovider.ExcelDataProviderObject) throws java.lang.InterruptedException requires a @DataProvider named : getData in class datadriven.dataprovider.ExcelDataProvider
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1081)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- DataProviderTest -->
  <testcase name="SearchPageTest" time="46.192" classname="datadriven.testscript.TC002MapSearchPage"/>
</testsuite> <!-- datadriven.testscript.TC002MapSearchPage -->
